apiVersion: v1
kind: Service
metadata:
  namespace: nacritan
  name: nacritan-backend-nginx-svc
  labels:
    tier: nacritan-backend
spec:
  selector:
    app: nginx
    tier: nacritan-backend
  ports:
  - protocol: TCP
    port: 80
    name: http
  - protocol: TCP
    port: 443
    name: https
