apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nacritan
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mariadb
            topologyKey: topology.kubernetes.io/zone

      containers:
      - name: api
        image: lordslair/nacritan:1.1.1
        command: ["/bin/sh"]
        args: ["-c", "while :; do sleep 12h; done;"]
        resources:
          limits:
            memory: 128Mi
            cpu: 200m
          requests:
            memory: 64Mi
            cpu: 100m
        env:
        # FLASK env vars
        - name: FLASK_ENV
          value: 'development'
        - name: FLASK_THREAD
          value: '--without-threads'
        # SQL env vars
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-host
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-port
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-pass
        - name: MYSQL_BASE
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-base
        # AUTH env vars
        - name: AUTH_TOKENS
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: api-auth-tokens
        # Python env vars
        - name: PYTHONUNBUFFERED
          value: 'True'
        - name: PYTHONIOENCODING
          value: 'UTF-8'
        # Loguru env vars
        - name: LOGURU_FORMAT
          value: '<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>level={level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'
        - name: LOGURU_COLORIZE
          value: 'true'
        - name: LOGURU_DEBUG_COLOR
          value: '<cyan><bold>'
        - name: LOGURU_LEVEL
          value: 'TRACE'
        # Other env vars
        - name: TZ
          value: 'Europe/Paris'
---
apiVersion: v1
kind: Service
metadata:
  namespace: nacritan
  name: api-svc
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 5000
