apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nacritan
  name: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backup
    spec:
      restartPolicy: Always

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - api
            topologyKey: topology.kubernetes.io/zone

      containers:
      - name: backup
        image: lordslair/easydbbackup:1.7.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 100m
        env:
        - name: SQLITE_DUMP
          value: 'False' # Boolean (True|False)
        - name: REDIS_DUMP
          value: 'False' # Boolean (True|False)
        - name: MYSQL_DUMP
          value: 'False'  # Boolean (True|False)
          # MONGODB specifics
        - name: MONGODB_DUMP
          value: 'True'  # Boolean (True|False)
        - name: MONGODB_EXPORT
          valueFrom:
            secretKeyRef:
              name: backup-secret
              key: backup-mongodb-export
        - name: MONGO_DB_LIST
          valueFrom:
            secretKeyRef:
              name: backup-secret
              key: backup-mongodb-dblist
        - name: MONGO_DB_HOST
          valueFrom:
            secretKeyRef:
              name: backup-secret
              key: backup-mongodb-host
        - name: MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-user
        - name: MONGO_DB_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-pass
        # RCLONE specifics
        - name: RCLONE_CONFIG_PCS_TYPE
          value: 'swift'
        - name: RCLONE_CONFIG_PCS_ENV_AUTH
          value: 'false'
        - name: RCLONE_CONFIG_PCS_AUTH_VERSION
          value: '3'
        - name: RCLONE_CONFIG_PCS_TENANT_DOMAIN
          value: 'default'
        - name: RCLONE_CONFIG_PCS_DOMAIN
          value: 'default'
        - name: RCLONE_CONFIG_PCS_AUTH
          valueFrom:
            secretKeyRef:
              name: pcs-secret
              key: pcs-auth
        - name: RCLONE_CONFIG_PCS_TENANT
          valueFrom:
            secretKeyRef:
              name: pcs-secret
              key: pcs-tenant
        - name: RCLONE_CONFIG_PCS_USER
          valueFrom:
            secretKeyRef:
              name: pcs-secret
              key: pcs-user
        - name: RCLONE_CONFIG_PCS_KEY
          valueFrom:
            secretKeyRef:
              name: pcs-secret
              key: pcs-key
        - name: RCLONE_CONFIG_PCS_REGION
          valueFrom:
            secretKeyRef:
              name: pcs-secret
              key: pcs-region
        - name: RCLONE_CONFIG_PCS_DIR
          valueFrom:
            secretKeyRef:
              name: backup-secret
              key: backup-dir
