---
apiVersion: v1
kind: Secret

metadata:
  namespace: nacritan
  name: mariadb-secret
type: Opaque
stringData:
  mariadb-root-password: '<mariadb-root-password>'
  mariadb-base: '<mariadb-base>'
  mariadb-host: '<mariadb-host>'
  mariadb-port: '<mariadb-port>'
  mariadb-user: '<mariadb-user>'
  mariadb-pass: '<mariadb-pass>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: nacritan
  name: api-secret
type: Opaque
stringData:
  api-auth-tokens: '<api-auth-tokens>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: nacritan
  name: pcs-secret
type: Opaque
stringData:
  pcs-auth: '<pcs-auth>'
  pcs-tenant: '<pcs-tenant>'
  pcs-key: '<pcs-key>'
  pcs-user: '<pcs-user>'
  pcs-region: '<pcs-region>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: nacritan
  name: backup-secret
type: Opaque
stringData:
  backup-db-list: '<backup-db-list>'
  backup-dir: '<backup-dir>'