---
apiVersion: v1
kind: Secret

metadata:
  namespace: nacritan
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-base: 'nacritan'
  mongodb-host: '<mongodb-host>'
  mongodb-user: 'nacritan'
  mongodb-pass: '<mongodb-pass>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: nacritan
  name: api-secret
type: Opaque
stringData:
  api-auth-tokens: '<api-auth-tokens>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: nacritan
  name: pcs-secret
type: Opaque
stringData:
  pcs-auth: '<pcs-auth>'
  pcs-tenant: '<pcs-tenant>'
  pcs-key: '<pcs-key>'
  pcs-user: '<pcs-user>'
  pcs-region: '<pcs-region>'
---
apiVersion: v1
kind: Secret

metadata:
  namespace: nacritan
  name: backup-secret
type: Opaque
stringData:
  backup-mongodb-export: 'True'
  backup-mongodb-dblist: 'nacritan'
  backup-mongodb-host: '<backup-mongodb-host>'
  backup-dir: '<backup-dir>'