apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nacritan
  name: nacritan-backend-backup
  labels:
    tier: nacritan-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
      tier: nacritan-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backup
        tier: nacritan-backend
    spec:
      restartPolicy: Always

      containers:
      - name: nacritan-backend-backup
        image: lordslair/easydbbackup:1.4.0
        imagePullPolicy: Always
        env:
        - name: SQLITE_DUMP
          value: '<SQLITE>' # Boolean (True|False)
        - name: SQLITE_DB
          value: '<SQLITE_FILE>'
        - name: SQLITE_PATH
          value: '<SQLITE_PATH>'
        - name: RCLONE_CONFIG_PCS_TYPE
          value: 'swift'
        - name: RCLONE_CONFIG_PCS_ENV_AUTH
          value: 'false'
        - name: RCLONE_CONFIG_PCS_AUTH_VERSION
          value: '3'
        - name: RCLONE_CONFIG_PCS_TENANT_DOMAIN
          value: 'default'
        - name: RCLONE_CONFIG_PCS_DOMAIN
          value: 'default'
        - name: RCLONE_CONFIG_PCS_AUTH
          value: 'https://auth.pcs.provider/v3/'
        - name: RCLONE_CONFIG_PCS_TENANT
          value: 'OS_TENANT_NAME'
        - name: RCLONE_CONFIG_PCS_USER
          value: 'OS_USERNAME'
        - name: RCLONE_CONFIG_PCS_KEY
          value: 'OS_PASSWORD'
        - name: RCLONE_CONFIG_PCS_REGION
          value: 'OS_REGION_NAME'
        - name: RCLONE_CONFIG_PCS_DIR
          value: 'backups/rclone'
        volumeMounts:
        - mountPath: /db
          name: db

      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: nacritan-backend-sqlite-db
